[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_GOOGLE_SHEETS_SPREADSHEET_ID = "1sNC2pMdLWIXKgWeyVjI9_hWOncoNSNp5ge8IPIWKiww"
  VITE_GOOGLE_SHEETS_WEB_APP_URL = "https://script.google.com/macros/s/AKfycbx1lkdE4x-k5ru3Ni--C2FFxqFMDt7N3jYz8qOSELYYMTu1LtX8qC0rpApC7VcL0WEg/exec"
  VITE_GOOGLE_SHEETS_API_KEY = "AIzaSyByzJJl0TUH4dGlgNdcpEoaRNHJZ3Tyh5Y"
  VITE_GOOGLE_SHEETS_SHEET_NAME = "sheets"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
